name: MLHB
channels:
  - conda-forge
  - defaults
dependencies:
  # common
  - mkl < 2022
  - ipython
  - jupyter
  - jupyterlab
  - matplotlib
  - nodejs>=12.0
  - numpy
  - pandas
  - pip
  - pytest
  - pytest-xdist
  - python=3.8.12
  - scikit-learn
  - scipy
  - swig # needed to compile box2d
  - tqdm
  - pip:
    - nbmerge
